package org.terraform.v26_3;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import org.terraform.coregen.TerraLootTable;
import static java.util.Map.entry;

import java.util.Map;

public class LootTableTranslator {

    // I am indeed formally trained to properly structure my code
    // I have however elected to completely ignore said training here
    // 28/3/2025 this fucking comment will follow me forever
    // 16/9/2026 This is now a Map.ofEntries call. Yay.
    public static final Map<TerraLootTable, ResourceKey<LootTable>> translationMap = Map.<TerraLootTable, ResourceKey<LootTable>>ofEntries(
            entry(TerraLootTable.SPAWN_BONUS_CHEST, BuiltInLootTables.SPAWN_BONUS_CHEST),
            entry(TerraLootTable.END_CITY_TREASURE, BuiltInLootTables.END_CITY_TREASURE),
            entry(TerraLootTable.SIMPLE_DUNGEON, BuiltInLootTables.SIMPLE_DUNGEON),
            entry(TerraLootTable.VILLAGE_WEAPONSMITH, BuiltInLootTables.VILLAGE_WEAPONSMITH),
            entry(TerraLootTable.VILLAGE_TOOLSMITH, BuiltInLootTables.VILLAGE_TOOLSMITH),
            entry(TerraLootTable.VILLAGE_ARMORER, BuiltInLootTables.VILLAGE_ARMORER),
            entry(TerraLootTable.VILLAGE_CARTOGRAPHER, BuiltInLootTables.VILLAGE_CARTOGRAPHER),
            entry(TerraLootTable.VILLAGE_MASON, BuiltInLootTables.VILLAGE_MASON),
            entry(TerraLootTable.VILLAGE_SHEPHERD, BuiltInLootTables.VILLAGE_SHEPHERD),
            entry(TerraLootTable.VILLAGE_BUTCHER, BuiltInLootTables.VILLAGE_BUTCHER),
            entry(TerraLootTable.VILLAGE_FLETCHER, BuiltInLootTables.VILLAGE_FLETCHER),
            entry(TerraLootTable.VILLAGE_FISHER, BuiltInLootTables.VILLAGE_FISHER),
            entry(TerraLootTable.VILLAGE_TANNERY, BuiltInLootTables.VILLAGE_TANNERY),
            entry(TerraLootTable.VILLAGE_TEMPLE, BuiltInLootTables.VILLAGE_TEMPLE),
            entry(TerraLootTable.VILLAGE_DESERT_HOUSE, BuiltInLootTables.VILLAGE_DESERT_HOUSE),
            entry(TerraLootTable.VILLAGE_PLAINS_HOUSE, BuiltInLootTables.VILLAGE_PLAINS_HOUSE),
            entry(TerraLootTable.VILLAGE_TAIGA_HOUSE, BuiltInLootTables.VILLAGE_TAIGA_HOUSE),
            entry(TerraLootTable.VILLAGE_SNOWY_HOUSE, BuiltInLootTables.VILLAGE_SNOWY_HOUSE),
            entry(TerraLootTable.VILLAGE_SAVANNA_HOUSE, BuiltInLootTables.VILLAGE_SAVANNA_HOUSE),
            entry(TerraLootTable.ABANDONED_MINESHAFT, BuiltInLootTables.ABANDONED_MINESHAFT),
            entry(TerraLootTable.NETHER_BRIDGE, BuiltInLootTables.NETHER_BRIDGE),
            entry(TerraLootTable.STRONGHOLD_LIBRARY, BuiltInLootTables.STRONGHOLD_LIBRARY),
            entry(TerraLootTable.STRONGHOLD_CROSSING, BuiltInLootTables.STRONGHOLD_CROSSING),
            entry(TerraLootTable.STRONGHOLD_CORRIDOR, BuiltInLootTables.STRONGHOLD_CORRIDOR),
            entry(TerraLootTable.DESERT_PYRAMID, BuiltInLootTables.DESERT_PYRAMID),
            entry(TerraLootTable.JUNGLE_TEMPLE, BuiltInLootTables.JUNGLE_TEMPLE),
            entry(TerraLootTable.JUNGLE_TEMPLE_DISPENSER, BuiltInLootTables.JUNGLE_TEMPLE_DISPENSER),
            entry(TerraLootTable.IGLOO_CHEST, BuiltInLootTables.IGLOO_CHEST),
            entry(TerraLootTable.WOODLAND_MANSION, BuiltInLootTables.WOODLAND_MANSION),
            entry(TerraLootTable.UNDERWATER_RUIN_SMALL, BuiltInLootTables.UNDERWATER_RUIN_SMALL),
            entry(TerraLootTable.UNDERWATER_RUIN_BIG, BuiltInLootTables.UNDERWATER_RUIN_BIG),
            entry(TerraLootTable.BURIED_TREASURE, BuiltInLootTables.BURIED_TREASURE),
            entry(TerraLootTable.SHIPWRECK_MAP, BuiltInLootTables.SHIPWRECK_MAP),
            entry(TerraLootTable.SHIPWRECK_SUPPLY, BuiltInLootTables.SHIPWRECK_SUPPLY),
            entry(TerraLootTable.SHIPWRECK_TREASURE, BuiltInLootTables.SHIPWRECK_TREASURE),
            entry(TerraLootTable.PILLAGER_OUTPOST, BuiltInLootTables.PILLAGER_OUTPOST),
            entry(TerraLootTable.BASTION_TREASURE, BuiltInLootTables.BASTION_TREASURE),
            entry(TerraLootTable.BASTION_OTHER, BuiltInLootTables.BASTION_OTHER),
            entry(TerraLootTable.BASTION_BRIDGE, BuiltInLootTables.BASTION_BRIDGE),
            entry(TerraLootTable.BASTION_HOGLIN_STABLE, BuiltInLootTables.BASTION_HOGLIN_STABLE),
            entry(TerraLootTable.ANCIENT_CITY, BuiltInLootTables.ANCIENT_CITY),
            entry(TerraLootTable.ANCIENT_CITY_ICE_BOX, BuiltInLootTables.ANCIENT_CITY_ICE_BOX),
            entry(TerraLootTable.RUINED_PORTAL, BuiltInLootTables.RUINED_PORTAL),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD, BuiltInLootTables.TRIAL_CHAMBERS_REWARD),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_COMMON, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_COMMON),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_RARE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_RARE),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_UNIQUE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_UNIQUE),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_RARE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_RARE),
            entry(TerraLootTable.TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE, BuiltInLootTables.TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE),
            entry(TerraLootTable.TRIAL_CHAMBERS_SUPPLY, BuiltInLootTables.TRIAL_CHAMBERS_SUPPLY),
            entry(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR),
            entry(TerraLootTable.TRIAL_CHAMBERS_INTERSECTION, BuiltInLootTables.TRIAL_CHAMBERS_INTERSECTION),
            entry(TerraLootTable.TRIAL_CHAMBERS_INTERSECTION_BARREL, BuiltInLootTables.TRIAL_CHAMBERS_INTERSECTION_BARREL),
            entry(TerraLootTable.TRIAL_CHAMBERS_ENTRANCE, BuiltInLootTables.TRIAL_CHAMBERS_ENTRANCE),
            entry(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR_DISPENSER),
            entry(TerraLootTable.TRIAL_CHAMBERS_CHAMBER_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_CHAMBER_DISPENSER),
            entry(TerraLootTable.TRIAL_CHAMBERS_WATER_DISPENSER, BuiltInLootTables.TRIAL_CHAMBERS_WATER_DISPENSER),
            entry(TerraLootTable.TRIAL_CHAMBERS_CORRIDOR_POT, BuiltInLootTables.TRIAL_CHAMBERS_CORRIDOR_POT),
            entry(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER),
            entry(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER_RANGED, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER_RANGED),
            entry(TerraLootTable.EQUIPMENT_TRIAL_CHAMBER_MELEE, BuiltInLootTables.EQUIPMENT_TRIAL_CHAMBER_MELEE),
            entry(TerraLootTable.FISHING, BuiltInLootTables.FISHING),
            entry(TerraLootTable.FISHING_JUNK, BuiltInLootTables.FISHING_JUNK),
            entry(TerraLootTable.FISHING_TREASURE, BuiltInLootTables.FISHING_TREASURE),
            entry(TerraLootTable.FISHING_FISH, BuiltInLootTables.FISHING_FISH),
            entry(TerraLootTable.CAT_MORNING_GIFT, BuiltInLootTables.CAT_MORNING_GIFT),
            entry(TerraLootTable.ARMORER_GIFT, BuiltInLootTables.ARMORER_GIFT),
            entry(TerraLootTable.BUTCHER_GIFT, BuiltInLootTables.BUTCHER_GIFT),
            entry(TerraLootTable.CARTOGRAPHER_GIFT, BuiltInLootTables.CARTOGRAPHER_GIFT),
            entry(TerraLootTable.CLERIC_GIFT, BuiltInLootTables.CLERIC_GIFT),
            entry(TerraLootTable.FARMER_GIFT, BuiltInLootTables.FARMER_GIFT),
            entry(TerraLootTable.FISHERMAN_GIFT, BuiltInLootTables.FISHERMAN_GIFT),
            entry(TerraLootTable.FLETCHER_GIFT, BuiltInLootTables.FLETCHER_GIFT),
            entry(TerraLootTable.LEATHERWORKER_GIFT, BuiltInLootTables.LEATHERWORKER_GIFT),
            entry(TerraLootTable.LIBRARIAN_GIFT, BuiltInLootTables.LIBRARIAN_GIFT),
            entry(TerraLootTable.MASON_GIFT, BuiltInLootTables.MASON_GIFT),
            entry(TerraLootTable.SHEPHERD_GIFT, BuiltInLootTables.SHEPHERD_GIFT),
            entry(TerraLootTable.TOOLSMITH_GIFT, BuiltInLootTables.TOOLSMITH_GIFT),
            entry(TerraLootTable.WEAPONSMITH_GIFT, BuiltInLootTables.WEAPONSMITH_GIFT),
            entry(TerraLootTable.UNEMPLOYED_GIFT, BuiltInLootTables.UNEMPLOYED_GIFT),
            entry(TerraLootTable.BABY_VILLAGER_GIFT, BuiltInLootTables.BABY_VILLAGER_GIFT),
            entry(TerraLootTable.SNIFFER_DIGGING, BuiltInLootTables.SNIFFER_DIGGING),
            entry(TerraLootTable.PANDA_SNEEZE, BuiltInLootTables.PANDA_SNEEZE),
            entry(TerraLootTable.CHICKEN_LAY, BuiltInLootTables.CHICKEN_LAY),
            entry(TerraLootTable.ARMADILLO_SHED, BuiltInLootTables.ARMADILLO_SHED),
            //entry(TerraLootTable.TURTLE_GROW, BuiltInLootTables.TURTLE_GROW),
            //entry(TerraLootTable.HARVEST_CAVE_VINE, BuiltInLootTables.HARVEST_CAVE_VINE),
            //entry(TerraLootTable.HARVEST_SWEET_BERRY_BUSH, BuiltInLootTables.HARVEST_SWEET_BERRY_BUSH),
            //entry(TerraLootTable.HARVEST_BEEHIVE, BuiltInLootTables.HARVEST_BEEHIVE),
            //entry(TerraLootTable.CARVE_PUMPKIN, BuiltInLootTables.CARVE_PUMPKIN),
            entry(TerraLootTable.PIGLIN_BARTERING, BuiltInLootTables.PIGLIN_BARTERING),
            entry(TerraLootTable.SPAWNER_TRIAL_CHAMBER_KEY, BuiltInLootTables.SPAWNER_TRIAL_CHAMBER_KEY),
            entry(TerraLootTable.SPAWNER_TRIAL_CHAMBER_CONSUMABLES, BuiltInLootTables.SPAWNER_TRIAL_CHAMBER_CONSUMABLES),
            entry(TerraLootTable.SPAWNER_OMINOUS_TRIAL_CHAMBER_KEY, BuiltInLootTables.SPAWNER_OMINOUS_TRIAL_CHAMBER_KEY),
            entry(TerraLootTable.SPAWNER_OMINOUS_TRIAL_CHAMBER_CONSUMABLES, BuiltInLootTables.SPAWNER_OMINOUS_TRIAL_CHAMBER_CONSUMABLES),
            entry(TerraLootTable.SPAWNER_TRIAL_ITEMS_TO_DROP_WHEN_OMINOUS, BuiltInLootTables.SPAWNER_TRIAL_ITEMS_TO_DROP_WHEN_OMINOUS),
            //entry(TerraLootTable.ARMADILLO_BRUSH, BuiltInLootTables.ARMADILLO_BRUSH),
            entry(TerraLootTable.BOGGED_SHEAR, BuiltInLootTables.BOGGED_SHEAR),
            entry(TerraLootTable.SHEAR_MOOSHROOM, BuiltInLootTables.SHEAR_MOOSHROOM),
            entry(TerraLootTable.SHEAR_RED_MOOSHROOM, BuiltInLootTables.SHEAR_RED_MOOSHROOM),
            entry(TerraLootTable.SHEAR_BROWN_MOOSHROOM, BuiltInLootTables.SHEAR_BROWN_MOOSHROOM),
            entry(TerraLootTable.SHEAR_SNOW_GOLEM, BuiltInLootTables.SHEAR_SNOW_GOLEM),
            entry(TerraLootTable.SHEAR_SHEEP, BuiltInLootTables.SHEAR_SHEEP),
            //entry(TerraLootTable.CHARGED_CREEPER, BuiltInLootTables.CHARGED_CREEPER),
            //entry(TerraLootTable.CHARGED_CREEPER_PIGLIN, BuiltInLootTables.CHARGED_CREEPER_PIGLIN),
            //entry(TerraLootTable.CHARGED_CREEPER_CREEPER, BuiltInLootTables.CHARGED_CREEPER_CREEPER),
            //entry(TerraLootTable.CHARGED_CREEPER_SKELETON, BuiltInLootTables.CHARGED_CREEPER_SKELETON),
            //entry(TerraLootTable.CHARGED_CREEPER_WITHER_SKELETON, BuiltInLootTables.CHARGED_CREEPER_WITHER_SKELETON),
            //entry(TerraLootTable.CHARGED_CREEPER_ZOMBIE, BuiltInLootTables.CHARGED_CREEPER_ZOMBIE),
            entry(TerraLootTable.DESERT_WELL_ARCHAEOLOGY, BuiltInLootTables.DESERT_WELL_ARCHAEOLOGY),
            entry(TerraLootTable.DESERT_PYRAMID_ARCHAEOLOGY, BuiltInLootTables.DESERT_PYRAMID_ARCHAEOLOGY),
            entry(TerraLootTable.TRAIL_RUINS_ARCHAEOLOGY_COMMON, BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_COMMON),
            entry(TerraLootTable.TRAIL_RUINS_ARCHAEOLOGY_RARE, BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_RARE),
            entry(TerraLootTable.OCEAN_RUIN_WARM_ARCHAEOLOGY, BuiltInLootTables.OCEAN_RUIN_WARM_ARCHAEOLOGY),
            entry(TerraLootTable.OCEAN_RUIN_COLD_ARCHAEOLOGY, BuiltInLootTables.OCEAN_RUIN_COLD_ARCHAEOLOGY),
            entry(TerraLootTable.ABANDONED_CAMP_BARREL, BuiltInLootTables.ABANDONED_CAMP_BARREL),
            entry(TerraLootTable.ABANDONED_CAMP_COMMON_CHEST, BuiltInLootTables.ABANDONED_CAMP_COMMON_CHEST),
            entry(TerraLootTable.ABANDONED_CAMP_SECRET_CHEST, BuiltInLootTables.ABANDONED_CAMP_SECRET_CHEST)
    );

}
